os: linux
dist: trusty
language: cpp
compiler: g++
sudo: required
  
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns
  - source /opt/qt58/bin/qt58-env.sh
  - /opt/qt58/bin/qmake PREFIX=/usr

script:
  - make
