os: linux
dist: bionic
language: cpp
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-bionic
  - sudo apt-get update
  - sudo apt-get install qt512base qt512multimedia cppcheck -y

install:
  - source /opt/qt5*/bin/qt5*-env.sh
  - /opt/qt5*/bin/qmake PREFIX=/usr

script:
  - make
  - cppcheck -i qrc_resources.cpp --enable=unusedFunction ./ 2> cppcheck_unused_f.txt
  - cppcheck -i qrc_resources.cpp --enable=warning,performance,style --error-exitcode=1 ./ 2> cppcheck.txt 
  - cat cppcheck_unused_f.txt
  - cat cppcheck.txt
